### ISSUE TITLE
Brush currently only works with touch

### ISSUE THREAD

**Issue by addyosmani** [samccone/moji-brush#2]
Testing against Canary/Dev/Stable, I can only get the emoji brush working if I'm emulating touch in DevTools. We might want to get it working all over thurr place. `onmousedown`/`onmouseup`? :cake: 

`onTouch` currently only checks against `touchstart` and `touchmove`.

``` js
  function onTouch(e) {
    for(let i = 0; i < e.touches.length; ++i) {
      let touch = e.touches[i];

      ctx.fillText(String.fromCodePoint(app.activeBrush),
                   touch.clientX * window.devicePixelRatio,
                   touch.clientY * window.devicePixelRatio);
    }

    e.preventDefault();
  }
```

**Comment by samccone** [comment]
WAI

but yeah we can make it work for mouse stuff as well :+1:

**Comment by sebmck** [comment]
yes this has left me very dissatisfied with this emoji brush tool. please fix this or i will be changing to another project, or i will write my own and publish it to npm.

**Comment by sebmck** [comment]
due to your delay in resolving this critical issue i have forked as [lobrush](https://github.com/kittens/lobrush). have a nice day mr cone.

**Comment by samccone** [comment]
Fixed
