### ISSUE TITLE
Undo should undo last stroke

### ISSUE THREAD

**Issue by benlesh** [samccone/moji-brush#26]
When I hit undo, I expected to undo the entire last stroke I did, and I thought maybe undo wasn't working. Took me a while to figure out that it was just doing one emoji at a time. Another side effect of this was that if you undo a _lot_ in a row, it sort of locks up while it renders each undo.

**Comment by benlesh** [comment]
Actually, undoing stroke by stroke for more than just last stroke would be good. Keeping a history of mementos after each stroke would be cool, because you could undo each stroke you've done.

**Comment by samccone** [comment]
:+1:

**Comment by joryphillips** [comment]
This [commit](https://github.com/samccone/moji-brush/commit/6c708699079f6c01adc85c5fcbea560d03d44f70) should have fixed that... it might need to be deployed to show up.

**Comment by samccone** [comment]
verified. I just needed to push the service worker force update code :)

if you open your app... close it... and open it ... it is good to go 💃

**Comment by benlesh** [comment]
Tried it last night, worked great!
