### ISSUE TITLE
More colors and shapes. 

### ISSUE THREAD

**Issue by benlesh** [samccone/moji-brush#28]
Solid emoji are the most generally useful, or emoji that are mostly one color. I wouldn't go overboard, I like the minimalist aspect of it, but maybe like four more colors. I wouldn't do more than 16.

**Comment by joryphillips** [comment]
Greet feedback, all around @blesh! 

I'm definitely of the mind the palette should be limited, but was also wondering if there should be an 'advanced' mode, with more colors/emoji and maybe fine-tuning of brush sizes, etc.
