### ISSUE TITLE
UX thoughts on brush/size picking

### ISSUE THREAD

**Issue by benlesh** [samccone/moji-brush#30]
The first time I chose my emoji, I tried to resize it by "pinching". It would be cool if you could resize and rotate the brush by "pinching and rotating" with two-fingers in the modal pop-up that shows the emoji when you first pick your color.

Also, I think you should show the emoji of choice on top of the color.

**Comment by samccone** [comment]
:+1: @joryphillips and I talked today about adding both of these features ... so +1

**Comment by benlesh** [comment]
Would also remove the `+/-` button from the bottom, as it would be unnecessary.

**Comment by joryphillips** [comment]
Quick thought: for fine control over the size, the slider is probably still necessary

**Comment by benlesh** [comment]
@joryphillips you're probably right. Could perhaps put a rotation control on that panel as well for fine tuning the rotation (If that feature is added)

**Comment by joryphillips** [comment]
@blesh @samccone I really really like the rotate brush idea.

**Comment by joryphillips** [comment]
Implemented, ya'll. Next up: more brushes via multiple taps in the palette.
