### ISSUE TITLE
save image should have a bottom frame bit that says.. made with moji-brush.com

### ISSUE THREAD

**Issue by samccone** [samccone/moji-brush#35]
@joryphillips thoughts?

**Comment by joryphillips** [comment]
@samccone Our canvas extends underneath the toolbar. We could put something there! It also makes it easy for the pros to crop out for when they publish to Dribbble.

**Comment by samccone** [comment]
+1

**Comment by samccone** [comment]
![image](https://cloud.githubusercontent.com/assets/883126/15982414/701d2618-2f3b-11e6-9c55-d736d9a6d46c.png)

yummm
